```{r <<ability_name_id>>-configs, include=FALSE}
ability_name_id <- "<<ability_name_id>>"
ability_name_cn <- ability_md %>%
  filter(nameid == ability_name_id) %>%
  pull(name)
scores_this_ability <- scores_origin %>%
  filter(abName == ability_name_cn) %>%
  rename(score = score_dev)
# descriptive statistics
ability_summary <- scores_this_ability %>%
  sum_tab(c("school", "grade"))
```

```{r <<ability_name_id>>-description, results="asis", echo=FALSE}
ability_md %>%
  filter(name == ability_name_cn) %>%
  # see 'build.R' at root directory for how `md` (Markdown) is generated
  pull(md) %>%
  cat()
```

```{r <<ability_name_id>>-histogram, echo=FALSE, warning=FALSE, message=FALSE, fig.cap=glue(descriptions$body$histogram$caption)}
scores_this_ability %>%
  ggplot(aes(score, fill = grade)) +
  geom_density(color = NA, alpha = 0.5) +
  scale_y_continuous(breaks = NULL, expand = c(0, 0)) +
  scale_fill_brewer(palette = "Dark2") +
  labs(x = "分数", y = "", fill = "") +
  set_theme_dist(base_family = text_family)
```

```{r <<ability_name_id>>-histogram-description, echo=FALSE, results="asis"}
descriptions$body$histogram$description %>%
  glue() %>%
  cat()
```

```{r <<ability_name_id>>-tab, echo=FALSE, warning=FALSE, message=FALSE}
ability_summary %>%
  rename(学校 = school, 年级 = grade) %>%
  knitr::kable(digits = 2, caption = glue(descriptions$body$table$caption))
```

```{r <<ability_name_id>>-tab-description, echo=FALSE, results="asis"}
descriptions$body$table$description %>%
  glue() %>%
  cat()
```

```{r <<ability_name_id>>-correlation, echo=FALSE, warning=FALSE, message=FALSE, results="asis", fig.cap=glue(descriptions$body$correlation$caption)}
subjects <- c("语文", "数学", "英语")
for (this_subj in subjects) {
  corr_plot <- scores_this_ability %>%
    filter(subject == this_subj) %>%
    ggplot(aes(score_std, performance)) +
    geom_point(size = 2, alpha = 0.4, color = "dodgerblue") +
    geom_smooth(method = "lm", size = 1, color = "red", fill = "indianred1") +
    facet_wrap(~grade, scales = "free") +
    labs(x = "能力得分", y = "学科成绩") +
    coord_fixed() +
    theme_minimal(base_size = 12, base_family = text_family)
  print(corr_plot)
  cat("\n\n")
}
```

```{r <<ability_name_id>>-correlation-description, echo=FALSE, results="asis"}
descriptions$body$correlation$description %>%
  glue() %>%
  cat()
```
