```{r {{ab_code}}-description, results='asis'}
render_heading_content(
  heading = "{{ab_name}}", hlevel = "{{ab_hlevel}}", style = "{{ab_hstyle}}", content = "{{ab_def}}"
) %>%
  cat()
```

```{r {{ab_code}}-histogram, fig.cap=str_glue("总体学生{{ab_name}}测评的分数分布")}
dataset_hist <- list(
  全体 = dataset,
  本校 = dataset_unit
) %>%
  bind_rows(.id = "group")
ggplot(dataset_hist, aes({{ab_code}}, fill = group)) +
  geom_density(color = NA, alpha = 0.5) +
  geom_vline(xintercept = mean(dataset_unit${{ab_code}}, na.rm = TRUE), color = "red") +
  scale_fill_brewer(palette = "Paired") +
  scale_y_continuous(breaks = NULL, expand = c(0, 0)) +
  labs(x = "分数", y = "", fill = "") +
  theme_minimal(base_size = 18, base_family = text_family) +
  theme(
    axis.title.x = element_text(margin = margin(t = 1, unit = "lines")),
    axis.line.x = element_line(),
    axis.ticks.x = element_line(),
    panel.grid = element_blank(),
    plot.margin = margin(1, 1, 1, 1, unit = "lines")
  )
stat_cmp <- broom::tidy(t.test({{ab_code}} ~ group, dataset_hist))
if (stat_cmp$p.value > 0.05) {
  diff_msg <- "和本项目测评全体学生差异不明显"
} else {
  if (stat_cmp$statistic > 0) {
    diff_msg <- "和本项目测评全体学生相比有一定差距"
  } else {
    diff_msg <- "比本项目测评全体学生明显更好"
  }
}
```

本校全部学生的{{ab_name}}测评的得分分布见图\@ref(fig:{{ab_code}}-histogram)，其中红色竖线表示本校学生的平均得分。本校学生的整体表现`r diff_msg`。

```{r {{ab_code}}-describe-school}
# get the level of each participant
dataset_with_level <- dataset %>%
  mutate(
    level = cut(
      {{ab_code}},
      breaks = score_levels$breaks,
      labels = score_levels$labels
    ) %>%
      fct_rev()
  )
dataset_unit_with_level <- dataset_with_level %>%
  filter(school == name_unit)
# summary statistics of whole and each report unit
stats_descr_region <- dataset_with_level %>%
  summarise(
    cnt = sum(!is.na({{ab_code}})),
    avg = mean({{ab_code}}, na.rm = TRUE),
    std = sd({{ab_code}}, na.rm = TRUE),
    top = max({{ab_code}}, na.rm = TRUE),
    med = median({{ab_code}}, na.rm = TRUE),
    btm = min({{ab_code}}, na.rm = TRUE)
  ) %>%
  add_column(group = "全体", .before = 1)
stats_descr_school <- dataset_unit_with_level %>%
  summarise(
    cnt = sum(!is.na({{ab_code}})),
    avg = mean({{ab_code}}, na.rm = TRUE),
    std = sd({{ab_code}}, na.rm = TRUE),
    top = max({{ab_code}}, na.rm = TRUE),
    med = median({{ab_code}}, na.rm = TRUE),
    btm = min({{ab_code}}, na.rm = TRUE)
  ) %>%
  add_column(group = "本校", .before = 1)
if (compare_unit != "school") {
  stats_descr_group <- dataset_unit_with_level %>%
    rename(group = !!compare_unit) %>%
    group_by(group) %>%
    summarise(
      cnt = sum(!is.na({{ab_code}})),
      avg = mean({{ab_code}}, na.rm = TRUE),
      std = sd({{ab_code}}, na.rm = TRUE),
      top = max({{ab_code}}, na.rm = TRUE),
      med = median({{ab_code}}, na.rm = TRUE),
      btm = min({{ab_code}}, na.rm = TRUE)
    ) %>%
    ungroup()
  stats_descr <- bind_rows(stats_descr_group, stats_descr_school, stats_descr_region) %>%
    mutate(group = factor(group, c(unique(stats_descr_group$group), "本校", "全体")))
} else {
  stats_descr <- bind_rows(stats_descr_school, stats_descr_region) %>%
    mutate(group = factor(group, c("本校", "全体")))
}
# output descriptive statistics as a table
stats_descr %>%
  knitr::kable(
    digits = 1,
    col.names = c(compare_unit_name, "实测人数", "平均数", "标准差", "最高分", "中位数", "最低分"),
    caption = str_glue("本次测评全体、本校及各{compare_unit_name}学生{{ab_name}}测评的整体表现详表")
  )
n_grps <- dataset_unit %>%
  filter(!is.na({{ab_code}})) %>%
  pull(!!compare_unit) %>%
  n_distinct()
diff_msg_avg <- ""
if (n_grps > 1) {
  dinfer_avg <- broom::tidy(aov(as.formula(str_glue("{{ab_code}} ~ {compare_unit}")), dataset_unit))
  if (n_grps > 2) {
    if (dinfer_avg$p.value[1] > 0.05) {
      dinfer_msg_avg <- str_glue("但是各{compare_unit_name}的表现差异不明显")
    } else {
      dinfer_msg_avg <- str_glue("并且各{compare_unit_name}的表现差异明显")
    }
    diff_msg_avg <- with(
      stats_descr_group,
      str_glue(
        "从学生的平均水平来看，",
        "{group[which.max(avg)]}学生的整体表现最好，",
        "而{group[which.min(avg)]}学生的整体表现相对较差，",
        "{dinfer_msg_avg}。"
      )
    )
  } else {
    if (dinfer_avg$p.value[1] > 0.05) {
      dinfer_msg_avg <- str_glue("但是两个{compare_unit_name}的表现差异不明显")
    } else {
      dinfer_msg_avg <- str_glue("并且两个{compare_unit_name}的表现差异明显")
    }
    diff_msg_avg <- with(
      stats_descr_group,
      str_glue(
        "从学生的平均水平来看，",
        "{group[which.max(avg)]}比{group[which.min(avg)]}学生的整体表现更好，",
        "{dinfer_msg_avg}。"
      )
    )
  }
}
```

表\@ref(tab:{{ab_code}}-describe-school)中展示了本次测评全体、本校和各年级的学生整体表现情况。`r diff_msg_avg`

```{r {{ab_code}}-levels-school}
# summary statistics of levels for whole and each school
stats_level_region <- dataset_with_level %>%
  mutate(cnt = sum(!is.na({{ab_code}}))) %>%
  group_by(level, cnt) %>%
  summarise(n_level = sum(!is.na(level))) %>%
  ungroup() %>%
  mutate(prop_level = n_level / cnt) %>%
  filter(!is.na(level)) %>%
  add_column(group = "全体", .before = 1)
stats_level_school <- dataset_unit_with_level %>%
  mutate(cnt = sum(!is.na({{ab_code}}))) %>%
  group_by(level, cnt) %>%
  summarise(n_level = sum(!is.na(level))) %>%
  ungroup() %>%
  mutate(prop_level = n_level / cnt) %>%
  filter(!is.na(level)) %>%
  add_column(group = "本校", .before = 1)
if (compare_unit != "school") {
  stats_level_group <- dataset_unit_with_level %>%
    rename(group = !!compare_unit) %>%
    group_by(group) %>%
    mutate(cnt = sum(!is.na({{ab_code}}))) %>%
    group_by(group, level, cnt) %>%
    summarise(n_level = sum(!is.na(level))) %>%
    ungroup() %>%
    mutate(prop_level = n_level / cnt) %>%
    filter(!is.na(level))
  stats_level <- bind_rows(stats_level_group, stats_level_school, stats_level_region) %>%
    mutate(group = factor(group, c(unique(stats_level_group$group), "本校", "全体"))) %>%
    complete(level, nesting(group, cnt), fill = list(n_level = 0, prop_level = 0))
} else {
  stats_level <- bind_rows(stats_level_school, stats_level_region) %>%
    mutate(group = factor(group, c("本校", "全体"))) %>%
    complete(level, nesting(group, cnt), fill = list(n_level = 0, prop_level = 0))
}
# output level statiscs as a table
stats_level %>%
  select(-prop_level) %>%
  spread(level, n_level, fill = "0") %>%
  knitr::kable(
    digits = 1,
    col.names = c("学校", "实测人数", rev(score_levels$labels)),
    caption = str_glue("本次测评全体、本校及各{compare_unit_name}学生{{ab_name}}测评的等级比例详表")
  )
```

表\@ref(tab:{{ab_code}}-levels-school)给出了所测各学校学生的各水平人数。划分方式如图\@ref(fig:blai-levels-rule)。

```{r {{ab_code}}-levels-rule, include="{{ab_code}}"=="blai", fig.width=12, fig.height=1, fig.cap="评分等级划分"}
lvls <- c("S", "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D")
grading <- tibble(
  label = factor(lvls, levels = lvls),
  y = c(0.05, rep(0.1, 9), 0.05),
  x = factor(1)
)
ggplot(grading, aes(x, y, fill = label, label = label)) +
  geom_bar(stat = "identity", position = "stack") +
  geom_text(position = position_stack(vjust = 0.5), color = "white") +
  coord_flip() +
  scale_fill_grey(guide = FALSE) +
  scale_y_continuous(
    breaks = c(0, cumsum(c(0.05, rep(0.1, 9), 0.05))),
    labels = c(
      expression(-infinity),
      sprintf(
        "%.0f", qnorm(c(seq(0.05, 0.95, by = 0.1))) * 15 + 100
      ),
      expression(infinity)
    )
  ) +
  labs(x = "", y = "") +
  theme_minimal() +
  theme(axis.text.y = element_blank(), panel.grid.minor = element_blank(), panel.grid.major.y = element_blank())
```

```{r {{ab_code}}-boxplot, include=n_grps > 1, fig.cap=str_glue("本次测评全体、本校及各{compare_unit_name}学生{{ab_name}}测评得分情况对比")}
if (compare_unit != "school") {
  order_med <- stats_descr_group %>%
    mutate(rnk = row_number(med)) %>%
    arrange(rnk)
  list(
    region = dataset,
    school = dataset_unit,
    by_group = dataset_unit
  ) %>%
    bind_rows(.id = "set") %>%
    mutate(
      group = case_when(
        set == "region" ~ "全体",
        set == "school" ~ "本校",
        TRUE ~ !!sym(compare_unit)
      )
    ) %>%
    mutate(group = factor(group, c(order_med$group, "本校", "全体"))) %>%
    filter(!group %in% with(stats_descr_group, group[which(cnt == 0)])) %>%
    ggplot(aes(group, {{ab_code}}, fill = set)) +
    geom_boxplot(outlier.color = NA, width = 0.5) +
    scale_fill_brewer(palette = "Pastel1", guide = FALSE) +
    labs(x = compare_unit_name, y = "分数", fill = "") +
    coord_flip(ylim = boxplot.stats(dataset_unit${{ab_code}})$stats[c(1, 5)]) +
    theme_minimal(base_size = 18, base_family = text_family) +
    theme(
      # x axis is at the bottom
      axis.title.x = element_text(margin = margin(t = 1, unit = "lines")),
      # disable facet panel labels
      strip.text = element_blank(),
      strip.background = element_blank(),
      # ensure facet panels are concatenated
      panel.spacing = unit(-0.5, "lines"),
      # remain major x grid only
      panel.grid = element_blank(),
      panel.grid.major.x = element_line(linetype = "dotdash", color = "grey")
    )
} else {
   list(
    region = dataset,
    school = dataset_unit
  ) %>%
    bind_rows(.id = "set") %>%
    mutate(
      group = case_when(
        set == "region" ~ "全体",
        set == "school" ~ "本校"
      )
    ) %>%
    mutate(group = factor(group, c("本校", "全体"))) %>%
    ggplot(aes(group, {{ab_code}}, fill = set)) +
    geom_boxplot(outlier.color = NA, width = 0.5) +
    scale_fill_brewer(palette = "Pastel1", guide = FALSE) +
    labs(x = compare_unit_name, y = "分数", fill = "") +
    coord_flip(ylim = boxplot.stats(dataset${{ab_code}})$stats[c(1, 5)]) +
    theme_minimal(base_size = 18, base_family = text_family) +
    theme(
      # x axis is at the bottom
      axis.title.x = element_text(margin = margin(t = 1, unit = "lines")),
      # disable facet panel labels
      strip.text = element_blank(),
      strip.background = element_blank(),
      # ensure facet panels are concatenated
      panel.spacing = unit(-0.5, "lines"),
      # remain major x grid only
      panel.grid = element_blank(),
      panel.grid.major.x = element_line(linetype = "dotdash", color = "grey")
    )
}
diff_msg_med <- ""
if (n_grps > 1) {
  dinfer_med <- broom::tidy(kruskal.test(as.formula(str_glue("{{ab_code}} ~ {compare_unit}")), dataset_unit))
  if (n_grps > 2) {
    if (dinfer_med$p.value[1] > 0.05) {
      diff_msg_med <- str_glue("但是各{compare_unit_name}的表现差异不明显")
    } else {
      diff_msg_med <- str_glue("并且各{compare_unit_name}的表现差异明显")
    }
    diff_msg_med <- with(
      stats_descr_group,
      str_glue(
        "从学生的中位数水平来看，",
        "{group[which.max(med)]}学生的整体表现最好，",
        "而{group[which.min(med)]}学生的整体表现相对较差，",
        "{diff_msg_med}。"
      )
    )
  } else {
    if (dinfer_med$p.value[1] > 0.05) {
      diff_msg_med <- str_glue("但是两个{compare_unit_name}的表现差异不明显")
    } else {
      diff_msg_med <- str_glue("并且两个{compare_unit_name}的表现差异明显")
    }
    diff_msg_med <- with(
      stats_descr_group,
      str_glue(
        "从学生的中位数水平来看，",
        "{group[which.max(med)]}比{group[which.min(med)]}学生的整体表现更好，",
        "{diff_msg_med}。"
      )
    )
  }
}
```

`r ifelse(n_grps > 1, paste0("本次测评学生的{{ab_name}}测评分数的分布区间如图\\@ref(fig:{{ab_code}}-boxplot)。", diff_msg_med), "")`
