```{r <<ab_id>>-configs, include=FALSE}
ab_id <- "<<ab_id>>"
ab_info <- as_tibble(
  config::get("ability", config = params$customer_id)
) %>%
  filter(id == ab_id)
ab_name_cn <- ab_info$name
scores_unit_this_ability <- scores_unit %>%
  filter(ab_name_en == ab_id)
scores_combined_this_ability <- list(
  full = scores_unit_this_ability,
  by_class = scores_unit_this_ability
) %>%
  bind_rows(.id = "set") %>%
  mutate(
    group = if_else(
      set == "full",
      "本校",
      class
    )
  )
# descriptive statistics
ability_summary_combined <- scores_combined_this_ability %>%
  group_by(set, group) %>%
  summarise(
    n = n(),
    avg = mean(score, na.rm = TRUE),
    std = sd(score, na.rm = TRUE),
    top = max(score, na.rm = TRUE),
    med = median(score, na.rm = TRUE),
    btm = min(score, na.rm = TRUE),
    A = sum(level == "A", na.rm = TRUE),
    B = sum(level == "B", na.rm = TRUE),
    C = sum(level == "C", na.rm = TRUE),
    D = sum(level == "D", na.rm = TRUE)
  ) %>%
  ungroup()
n_cls <- n_distinct(scores_unit_this_ability$class)
order_med <- ability_summary_combined %>%
  arrange(set, med) %>%
  pull(group)
```

```{r <<ab_id>>-description, results="asis", echo=FALSE}
ab_info %>%
  mutate(
    md = render_heading_content(
      heading = name, content = description,
      hlevel = hlevel, style = style
    )
  ) %>%
  pull(md) %>%
  cat()
```

```{r <<ab_id>>-histogram, echo=FALSE, warning=FALSE, message=FALSE, fig.cap=str_glue("本校学生{ab_name_cn}测评的分数分布对比")}
scores_unit_this_ability %>%
  ggplot(aes(score)) +
  geom_density(color = NA, fill = "lightblue", alpha = 0.5) +
  geom_vline(xintercept = mean(scores_unit$score), color = "red") +
  scale_y_continuous(breaks = NULL, expand = c(0, 0)) +
  labs(x = "分数", y = "", fill = "") +
  theme_minimal(base_size = 18, base_family = text_family) +
  theme(
    axis.title.x = element_text(margin = margin(t = 1, unit = "lines")),
    axis.line.x = element_line(),
    axis.ticks.x = element_line(),
    panel.grid = element_blank(),
    plot.margin = margin(1, 1, 1, 1, unit = "lines")
  )
```

本校学生总体的`r ab_name_cn`测评的得分分布见图\@ref(fig:<<ab_id>>-histogram)。

```{r <<ab_id>>-tab, echo=FALSE, warning=FALSE, message=FALSE}
ability_summary_combined %>%
  select(-set) %>%
  knitr::kable(
    digits = 2,
    col.names = c("", "人数", "平均数", "标准差", "最高分", "中位数", "最低分", LETTERS[1:4]),
    caption = str_glue("本校和各班学生{ab_name_cn}测评的整体表现详表")
  )
```

本校共施测`r n_cls`个班级。表\@ref(tab:<<ab_id>>-tab)中展示了本校和各班的学生整体表现情况。其中，**水平A**：优秀；**水平B**：良好；**水平C**：中等；**水平D**：较差。

```{r <<ab_id>>-boxplot, echo=FALSE, warning=FALSE, message=FALSE, fig.cap=str_glue("本校和各班学生{ab_name_cn}测评的得分情况对比")}
scores_combined_this_ability %>%
  mutate(group = factor(group, order_med)) %>%
  ggplot(aes(group, score, fill = set)) +
  geom_boxplot(outlier.color = NA, width = 0.5) +
  scale_fill_brewer(palette = "Pastel1", guide = FALSE) +
  labs(x = "", y = "分数", fill = "") +
  coord_flip(ylim = boxplot.stats(scores_combined_this_ability$score)$stats[c(1, 5)]) +
  theme_minimal(base_size = 10, base_family = text_family) +
  theme(
    # x axis is at the bottom
    axis.title.x = element_text(margin = margin(t = 1, unit = "lines")),
    # disable facet panel labels
    strip.text = element_blank(),
    strip.background = element_blank(),
    # ensure facet panels are concatenated
    panel.spacing = unit(-0.5, "lines"),
    # remain major x grid only
    panel.grid = element_blank(),
    panel.grid.major.x = element_line(linetype = "dotdash", color = "grey")
  )
```

本校和各班的`r ab_name_cn`测评分数的分布区间如图\@ref(fig:<<ab_id>>-boxplot)。

```{r <<ab_id>>-grading, echo=FALSE, warning=FALSE, message=FALSE, fig.cap=str_glue("本校和各班{ab_name_cn}测评的各水平人数比例")}
ability_summary_combined %>%
  select(group, n, A:D) %>%
  add_row(
    group = "全国平均", n = 100,
    A = 10, B = 20, C = 40, D = 30
  ) %>%
  mutate(
    group = factor(
      group, levels = c(order_med, "全国平均")
    )
  ) %>%
  gather(level, count, A:D) %>%
  mutate(
    prop = count / n * 100,
    n_label = if_else(count == 0, NA_real_, count),
    prop_label = if_else(round(prop) == 0, NA_real_, round(prop))
  ) %>%
  ggplot(aes(group, prop, fill = level, label = n_label)) +
  geom_col(position = "stack", width = 0.5) +
  geom_text(position = position_stack(vjust = 0.5), size = 3) +
  scale_fill_brewer(palette = "Blues") +
  scale_y_continuous(breaks = c(0, 30, 70, 90, 100)) +
  labs(x = "", y = "比例（%）", fill = "") +
  coord_flip() +
  theme_minimal(base_size = 10, base_family = text_family) +
  theme(
    # x axis is at the bottom
    axis.title.x = element_text(margin = margin(t = 1, unit = "lines")),
    # disable facet panel labels
    strip.text = element_blank(),
    strip.background = element_blank(),
    # ensure facet panels are concatenated
    panel.spacing = unit(-0.5, "lines"),
    # remain major x grid only
    panel.grid = element_blank(),
    panel.grid.major.x = element_line(linetype = "dotdash", color = "grey")
  )
```

本校学生总体在`r ab_name_cn`测评中各个水平的人数比例如图\@ref(fig:<<ab_id>>-grading)。每个班级的学生从等级优秀到不足的占比情况存在差异，应该重点关注在等级D中占比较大的班级对学生的`r ab_name_cn`进行有计划的训练和干预。其中，**水平A**：优秀；**水平B**：良好；**水平C**：中等；**水平D**：较差。
