# 报告正文

```{r setup-body-content}
# default child file pattern: {part}/{report_unit}/{report_type}/{customer_id}
# TODO: use `region_id` to replace `customer_id`
body_child_file <- file.path(
  getOption("reports.archytype"),
  "body", params$report_unit, params$report_type,
  str_c(params$customer_id, ".Rmd")
)
# if the file not found, use a default one
if (!file.exists(body_child_file)) {
  body_child_file <- file.path(
    getOption("reports.archytype"),
    "body", params$report_unit, params$report_type, "default.Rmd"
  )
}
score_levels <- config::get("score.level")
```

```{r get-blai-content, results='asis'}
ab_code <- "blai"
ab_name <- "大脑学习能力"
ab_hlevel <- 2
ab_hstyle <- "标题2-编号"
ab_def <- "大脑学习能力反映了注意力、记忆力、自控力、反应力和思维力这五个方面的综合水平，分数越高代表大脑学习能力的综合发展水平越高。"
text_to_render_blai <- knitr::knit_expand(body_child_file)
cat(knitr::knit(text = text_to_render_blai, quiet = TRUE))
```

::: {custom-style="标题2-编号-换页"}
## 各能力单独报告
:::

```{r get-body-content, results='asis'}
report_abilities <- config::get("report.ability") %>%
  as_tibble()
n_abilities <- nrow(report_abilities)
text_to_render <- character(length = n_abilities)
for (i_row in 1:n_abilities) {
  ab_code <- report_abilities[[i_row, "code"]]
  ab_name <- report_abilities[[i_row, "name"]]
  ab_hlevel <- report_abilities[[i_row, "hlevel"]]
  ab_hstyle <- report_abilities[[i_row, "hstyle"]]
  ab_def <- report_abilities[[i_row, "def"]]
  if (all(is.na(dataset_unit[[ab_code]]))) {
    text_to_render <- knitr::knit_expand(
      file.path(
        getOption("reports.archytype"),
        "body.null.Rmd"
      )
    )
  } else {
    text_to_render <- knitr::knit_expand(body_child_file)
  }
  cat(knitr::knit(text = text_to_render, quiet = TRUE))
  cat("\n\n")
}
```
