# 总结与建议

<!-- ## 结果综合分析

通过对测评结果的综合分析，我们可以看到，参与“脑·育”项目的本区学生基础学习能力得分存在如下几个重要特点：

1. 总体得分水平较高。从整体水平上看，学生的平均分达到106，超过同年龄的平均水平，而且各个子能力维度的平均分数都在100分以上，说明各个能力也超过了同年龄平均水平，体现了十一学校本届学生良好的基础素质；
1. 各个能力之间发展不平衡。从各个能力维度看，我们发现本届初一学生体现为思维力和记忆力较强，但是自控力相对较弱的特点。而自控能力是初中生认知能力发展的重要时期，为我们下一期工作的重点提供了指导；
1. 学生能力发展差异大。虽然本届学生的整体水平较高，但也存在现在的个体差异。无论总分还是各个能力维度得分最高分和最低分的差异都非常大，最高在120分以上，而最低在50分左右。其中思维力，记忆力这些总体表现很好的维度，个体差异的水平也很大。另外，我们初步筛选的后50名学生，其得分都在同龄人平均分之下，具有很大的提升空间；
1. 学生能力发展不平衡。我们发现不同的学生在不同能力维度的发展不完全平衡，只有少数学生在各个维度均衡发展；但还有很多学生在某些维度表现突出，但另外一些维度相对薄弱。 -->

## 总体发展建议

### 重视对学生基础学习能力的发展性评价

大量研究表明，大脑基础学习能力是预测学生学业表现的重要指标。比如，德国一项研究表明，在很多领域，大脑基础学习能力指标都是已知的预测学业成绩的最好指标。一般智力与学业成绩的相关通常在0.5左右。在另一项研究中，研究人员比较了智力因素，动机因素和两者共同作用对语文，数学和科学成绩的影响。结果发现，智力因素对语文成绩的贡献大概为45%，对数学的贡献为53%，对科学的贡献高达90%。在一项中国进行的研究中，研究人员发现，工作记忆和一般智力可以解释17.8 %的语言分数，36.4%的数学分数，而动机因素对学习只有很小的影响。上面只是列举了几个有代表性的研究案例。事实上，除了这些研究，还有很多发现都一致地强调了基础学习能力与学业表现的重要关联。

除了一般智力因素以外，学科学习还需要一些特殊的基础学科能力。这些基础学科能力包括语文，数学，科学，艺术等各个学科学习所必需的，重要的基础性能力。这些能力区别于对学科知识的掌握，但对学科知识的掌握具有重要的影响。比如，伦敦大学学院教育学院的Emily Farran团队研究发现中小学生的空间能力与数学能力有很高的相关（0.479）。进一步的回归分析发现，在考虑了阅读能力的贡献后，空间能力仍然能很好地预测数学能力。我们在参与北京市脑计划的研究中发现，中学生认知能力和语文、数学和英语成绩的表现有显著关联。另外，对区域教育质量监测的研究发现，初中生数学成绩的不仅与与基础学习能力存在显著相关，也与数学学科基础能力，包括空间能力，计算能力，数感等能力存在密切关系，基础学习能力和基础数学能力之间也存在显著相关。基础学习能力和学科基础能力对预测学习成绩有独特的贡献。

总之，国内外大量研究表明，基于脑科学的学生基础学习能力测评可以快速、高效地评测学生基础学习能力的长板和短板，并在线追踪每个学生的发展变化和进步情况，形成学生发展大数据；而且，学科基础能力与各个学科成绩存在着高相关，充分了解学生的学习能力情况，可以为学生的学业成绩和行为表现提供科学的诊断和原因分析。值得注意的是，在未来测评的实施和报告的使用上，需要把评价深入到学习的每个环节，实现测评的常态化和过程化，这样既能减小误差，提高测评精度，同时也有助于建立个体的成长性档案。另外，还需要强化测评的诊断功能，强化成长性评价，从而能对学生的学习能力进行全面诊断，找出学习困难的真正原因，进而促成有针对性的训练，指导学习力的培养。与行为数据一起，实现对个体学习能力的更精细刻画。

### 尊重学生大脑发育与学习规律

提高学习效率，就是要针对不同阶段大脑发展的特征，制定有针对性的学习目标和学习任务。大脑每个区域的发育都存在“机会窗口”，依据这个“机会窗口”学习，可以事半功倍；如果错过了这个“机会窗口”，则需要花很多时间来弥补。

比如，小学阶段是大脑前额叶发展的关键时期，也就是前额叶发展的“机会窗口”，也是我们注意、记忆、思维和自控等一般学习能力发展的重要阶段。这个阶段的孩子本身面临的学习任务并不太重，所面临考试升学的压力也不太大，这为提高孩子的学习能力提供了非常好的机会。但在实践中，老师和家长对空出来的时间究竟用来做什么并不十分明确。有的家长在培训机构的推动下，把时间用来提前学习高年级甚至初中的课程，学习奥数，学习STEM、机器人编程，发展兴趣特长等。根据孩子的兴趣爱好发展兴趣特长当然值得鼓励，但超前学习却是毫无意义的。相反，在这个阶段培养扎实的学习能力，提高孩子的注意、记忆、思维、自控等能力，培养良好的学习习惯，提升学习的兴趣和动机，比提前掌握大量的知识更为重要。

有效的学习还需要遵循学习的规律。首先，提高学习效率，促进学习的长期保持和有效迁移的一个前提条件是，要创造适度难度的学习环境，让大脑的资源做充分的参与。比如，分散学习能够促进大脑的参与，有更多的大脑资源参与到学习过程当中，从而促进学习效果的保持。学习和记忆里还有很多规律，包括组块的规律，迁移的规律，以及元记忆策略等等，这些都是我们科学、高效学习的基础。通过科学利用大脑学习的规律，能够充分调动大脑的潜能，真正做到事半功倍，举一反三！其次，人有多套不同的学习系统，有的是情绪的学习，有的知识的学习，有的是感知觉的学习，有的是运动技能的学习。需要通过恰当的方式让正确的大脑学习系统参与到其中。 最后，有效的学习需要把大脑中先前的记忆重新唤醒，然后才能进行巩固或者修改。从这个意义上讲，学习就是不断改变大脑中的记忆痕迹的过程。我们的一些学习方法，比如死记硬背或者简单机械重复等，往往并不能有效唤醒先前的记忆痕迹，从而达不到训练的效果。相反，有的时候，比如在我们回忆的时候，在我们休息的时候，在我们睡觉的时候，我们的记忆可以得到更有效的唤醒并重新组织，形成有机的知识网络。

### 完善促进学生学习能力发展的课程体系

课程是教育的载体，是教育实施的工具和媒介，在教育体系中处于中心地位，是教与学的核心。基于脑科学的有效学习发生及常态化，需要靠科学且体系化的课程建设加以贯彻和完成。构建脑科学背景下的课程体系，是深化学习变革，实现教育之新时代任务的迫切需要。为了推动脑科学与学校教学的融合，更好促进学生学习能力发展，学校可以从基础性课程、融合性课程、辅助性课程三个方面加强学课程建设。

“脑育”课程是基础工程。开展专门性脑育课，具有两个方面的重要功能和作用。首先，脑科学是一个庞大的知识体系，有很多对学生大脑发育和开发有益的知识需要普及。 对大脑基本的构成，工作原理，发展阶段和过程等基础知识的了解，是学生和家长科学的“使用脑”，“保护脑”和“开发脑”的基础，也是老师进行基于脑科学的教学的理论基础。其次，专门脑育课程是学习能力发展性评价和学习能力训练提升的重要阵地。包括注意力、记忆力、思维力、反应力和自控力等核心学习能力的培养，可以通过针对性学习和训练课程具体实施。每周开设1节脑育课程，组织学校的心理老师，班主任老师，骨干教师进行培训、教研和实际教学。不仅可以明显提高学生的学能力，同时老师们通过教研，备课和讲授，也丰富和巩固自己的脑科学知识和基于脑科学的课堂实践能力，有助于他们进一步把脑科学理论和方法融入日常课堂教学。

脑科学与学科融合是关键目标。基于脑科学的学习能力提升，与现有国家课程有机融合，才能在小学教育中产生强大的生命力和持久潜在的影响力。这种融合，可以从两个维度展开尝试。其一是核心学习能力即注意力、记忆力、思维力、反应力和自控力等在课程教学中的有意识强化；其二是准确把握学科基础能力，在课程教学中与特定能力和知识点培养建立连接，从而达到潜移默化训练和提升的效果。比如，学科教学中可以根据教学目标及文本材料的实际需要，创设生动且生活化的情境，吸引孩子参与学习的过程，在学生疲惫和容易走神的时候设置活动或者游戏环节，就是不断强化与训练孩子注意力和自控力的最好融合方式。再比如，在学科教学中，可以灵活运用想象、联想、意义、直观、谐音等诸多方法，有意识强化对教学内容的记忆，并讲授其中的原理，实现知识、方法策略与能力的同步提升等。在课程目标上，结合学科知识的目标，强化大脑基础学习能力和学科能力的培养。比如数学学习中的数量加工、空间几何能力、数感，工作记忆等能力，以及比较、分类、概括、类比、归纳演绎、分析综合等思维能力等。语文学习中，形音联系、语音语素意识以及更高一层的读写和理解能力等都是语文需要重点培养的能力。

脑科学指导下的综合辅助课程是有效补充。所谓辅助性课程，就是在脑科学理论指导下，能够有效辅助学生学习能力提升的特色活动或主题性活动。比如，通过体育课程来促进有氧运动，促进大脑发育和认知能力提升；通过丰富的艺术课程，可以生成创造力、想象力、精密性和审美反应等思维技巧，还可生成运用多视角观察与模仿能力，这些能力能够对跨学科的学习产生更深远的影响。通过灵活性、针对性与趣味性的活动课程，比如数学活动节，“跳蚤市场”，语文活动节、英语活动节等，均通过生动活泼形式多样的活动，对孩子核心学习能力及学科基础学习能力进行有目的的训练和强化。

### 强化特殊学生的专项学习能力训练

通过科学测评揭示不同学生的学习能力特点，可以开展有针对性的学习能力训练，从而提高学习能力，促进学习表现。在这个方面，目前已经有了大量的研究证据。比如，英国诺森比亚大学的研究者Joni Holmes在国际著名发展心理学学术期刊《Developmental Science》发表研究成果，他们发现，对工作记忆较差的学生进行认知能力训练能够提高其工作记忆表现，同时数学能力也能得到显著的提高。耶鲁大学的认知训练研究结果发现，通过对工作记忆，注意力等的训练，可以有效提高学生的一般认知能力，同时提高他们在阅读和数学上的学习表现。其中，我们与北医六院合作，针对学生多动症的认知训练干预，也取得了显著的效果。

另外，针对不同学科的关键学习能力进行训练，也可以有效改善学生的学科学习成绩。比如，苏黎世大学儿童医院磁共振研究中心的K. Kucian团队研究采用数字估计训练任务，对存在计算障碍的学生以及正常学生分别执行长达五周的训练。发现训练对于两组学生都有一定效果，但是对于存在计算障碍的学生而言，训练效果更大。密歇根州立大学教育学院的Yi-Ling Cheng团队采用持续40分钟的心理旋转挑战题目对学生进行训练。结果显示，相对于控制组而言，训练组学生的数学能力表现在训练后有了明显提升。

大量研究表明，我们可以通过对某些能力欠缺的学生进行有效干预和训练，从而达到真实提高其基础学习能力的目标。这一切离不开长期的、针对性地、有效的干预措施，只有建立长效且定期的干预方案才能真正实现测评的意义，才能真正达到提高学生整体素质以及学业成绩的目的。

## 具体实施措施建议

综合小学生大脑发育的总体特征，以及本次测评中学生在大脑能力能力发展上的特点，结合脑科学与教育融合的基本规律，以及国际国内在这方面的先进经验和有益实践，我们特作出如下建议：

首先，建议加强对全体学生在前额叶成熟方面的针对性干预。通过开设大脑课程，讲述青春期大脑发育，认知发展和情绪控制等方面的基础知识，青春期年龄特点，发展规律，生活中的应对方式和认知技能，以及通过有氧运动，认知训练，社会情绪技能教授和练习等方式，促进学生的大脑前额叶发展，提升大脑的功能，缓解情绪和认知压力，提高学习效率和心理健康水平，具有积极的作用。

第二，针对部分学生总体学习能力偏低的特点，我们建议针对这些学生进一步重点干预和指导。考虑到不同的学生的发展能力特征不同，我们建议对整体学习能力发展有待提升的学生进行进一步的深度测查，全面深入了解各个学生的发展能力状况，在自控力，注意力， 思维力，反应力和记忆力等五大基础学习能力等方面的发展模式，从而为进一步个性化的干预提供基础。

第三，加强脑科学课程建设，推动脑科学与教育实践的有机融合。建议针对全体学生开展“脑育”基础课程，加强脑科学基础知识普及，学习能力发展性评价和针对性训练。尝试开展脑科学与学科教学的融合，提高课堂教学的科学化水平。特别注重在课堂中加强对相对薄弱能力的培养。最后，结合学校自身特色，开展丰富多彩和活动课程，教学节或者大脑节等活动，让脑科学思想和实践深度融合校园。

第四，基于脑科学“因脑量材，因脑施教”的思想，为不同学生提供个性化的教育内容和训练计划。结合学生的学习能力发展状况，通过分层走班，课后俱乐部、分类教学等形式，在教学内容，教学难度和教学形式等各个方面为学生制定更适宜的教学安排，提升学习的动力和学习效果。

第五，加强对特殊学生的基础学习的培养，特别是对于学习力发展不足，以及发展不均衡的学生上（见附件名单），建议制定专门的方案，为这些学生的学习能力提升提供针对性的解决方案，为后面长期的学习打下能力的基础。

最后，建议加强全体老师在脑科学与教育融合领域的培训，增强老师基于脑科学教学的意识，知识和能力，把脑科学的基础理论，把学生的大脑发育特征，与学科的教育，课程的设置、学校活动的组织等充分的结合，从而把基于脑的办学思想和实践在全校普及。
