```{r <<ability_name>>-configs, include=FALSE}
ability_name <- "<<ability_name>>"
ability_name_cn <- ability_names[ability_name]
scores_this_ability <- scores_combined %>%
  filter(ability == ability_name_cn)
bp_stats <- boxplot.stats(scores_this_ability$score)
```

```{r <<ability_name>>-description, results="asis", echo=FALSE}
ability_info %>%
  filter(name == ability_name_cn) %>%
  # see 'build.R' at root directory for how `md` (Markdown) is generated
  pull(md) %>%
  cat()
cat("\n\n")
```

```{r <<ability_name>>-histogram, echo=FALSE, warning=FALSE, message=FALSE, fig.cap=glue(descriptions$body$histogram$caption)}
scores_this_ability %>%
  filter(region != "各班") %>%
  ggplot(aes(score, fill = region)) +
  geom_density(color = NA, alpha = 0.5) +
  scale_y_continuous(breaks = NULL, expand = c(0, 0)) +
  scale_fill_brewer(palette = "Paired") +
  labs(x = "分数", y = "", fill = "") +
  set_theme_dist(base_family = text_family)
```

```{r <<ability_name>>-histogram-description, echo=FALSE, results="asis"}
# `diff_msg` is used in description
diff_msg <- scores_this_ability %>% 
  filter(region != "各班") %>% 
  group_by(region) %>% 
  summarise(score = list(score)) %>% 
  spread(region, score) %>% 
  mutate(
    p_value = t.test(unlist(本校), unlist(本区))$p.value,
    t_value = t.test(unlist(本校), unlist(本区))$statistic,
    msg = case_when(
      p_value > 0.05 ~ descriptions$body$histogram$note$equal,
      p_value <= 0.05 & t_value > 0 ~ descriptions$body$histogram$note$large,
      p_value <= 0.05 & t_value < 0 ~ descriptions$body$histogram$note$small
    )
  ) %>% 
  pull(msg)
descriptions$body$histogram$description %>% 
  glue() %>% 
  cat()
```

```{r <<ability_name>>-boxplot, echo=FALSE, warning=FALSE, message=FALSE, fig.cap=glue(descriptions$body$boxplot$caption)}
ggplot(scores_this_ability, aes(cls, score, fill = cls)) +
  geom_boxplot(outlier.color = NA, width = 0.5) +
  facet_wrap(~ region, scales = "free_y", ncol = 1) +
  scale_y_continuous(limits = bp_stats$stats[c(1, 5)]) +
  scale_fill_brewer(palette = "Pastel1", guide = FALSE) +
  labs(x = "", y = "分数", fill = "") +
  coord_flip() +
  set_theme_panels(base_family = text_family)
```

```{r <<ability_name>>-boxplot-description, echo=FALSE, results="asis"}
# `n_cls`, `best_cls_med`, `worst_cls_med` are required
score_meds <- scores_this_ability %>% 
  filter(region == "各班") %>% 
  group_by(cls) %>% 
  summarise(med = median(score, na.rm = TRUE)) %>% 
  arrange(desc(med))
n_cls <- nrow(score_meds)
best_cls_med <- first(score_meds$cls)
worst_cls_med <- last(score_meds$cls)
descriptions$body$boxplot$description %>% 
  glue() %>% 
  cat()
```

```{r <<ability_name>>-tab, echo=FALSE, warning=FALSE, message=FALSE}
ability_summary <- scores_this_ability %>%
  sum_tab()
ability_summary %>%
  rename(` ` = cls) %>%
  select(-region) %>%
  knitr::kable(digits = 2, caption = glue(descriptions$body$table$caption))
```

```{r <<ability_name>>-tab-description, echo=FALSE, results="asis"}
# `best_cls`, `worst_cls` are required
ability_summary_cls <- ability_summary %>% 
  filter(region == "各班") %>% 
  arrange(desc(平均分))
best_cls <- first(ability_summary_cls$cls)
worst_cls <- last(ability_summary_cls$cls)
descriptions$body$table$description %>% 
  glue() %>% 
  cat()
```

```{r <<ability_name>>-grading, echo=FALSE, warning=FALSE, message=FALSE, fig.cap=glue(descriptions$body$grading$caption)}
ability_summary %>%
  gather(level, n, A:D) %>%
  mutate(
    prop = n / 实测人数 * 100,
    prop_label = if_else(round(prop) == 0, NA_real_, round(prop))
  ) %>%
  ggplot(aes(cls, prop, fill = level, label = prop_label)) +
  geom_col(position = "stack", width = 0.5) +
  geom_text(position = position_stack(vjust = 0.5), size = 3) +
  facet_wrap(~ region, scales = "free_y", ncol = 1) +
  scale_fill_brewer(palette = "Blues") +
  labs(x = "", y = "比例（%）", fill = "") +
  coord_flip() +
  set_theme_panels(base_family = text_family)
```

```{r <<ability_name>>-grading-description, echo=FALSE, results="asis"}
descriptions$body$grading$description %>% 
  glue() %>% 
  cat()
```
