```{r assess-date-prep, include=FALSE}
user_vars <- names(user_info)
users_to_report <- user_info %>%
  filter(school %in% config::get("customer.organizations")) %>%
  left_join(
    ability_scores %>%
      select(-ab_name) %>%
      spread(ab_code, score),
    by = "user_id"
  ) %>%
  filter(grade != "1年级") %>%
  group_by(school, full_class) %>%
  mutate(n = sum(!is.na(assess_time))) %>%
  filter(n > 0) %>%
  select(one_of(user_vars))
assess_date <- ability_scores %>%
  semi_join(users_to_report, by = "user_id") %>%
  pull(assess_time) %>%
  range(finite = TRUE) %>%
  format.Date("%Y年%m月")
if (any(duplicated(assess_date))) assess_date <- assess_date[1]
if (length(assess_date) == 1) {
  assess_date_inline <- assess_date
} else {
  assess_date_inline <- paste(assess_date, collapse = "到")
}
```

## 项目背景介绍

<!--TODO: add more details here-->

这份报告描述了于`r assess_date_inline`在成都市教育科学研究院主持下进行的“脑科学与未来教育”（简称“脑·育”）项目中学生的表现。

## 学生参加测评的情况

```{r school-summary, fig.height=8, fig.width=10}
ability_scores %>%
  select(-ab_name) %>%
  spread(ab_code, score) %>%
  right_join(users_to_report, by = "user_id") %>%
  group_by(school) %>%
  summarise(
    n_total = n(),
    assessed = sum(!is.na(assess_time)),
    missing = n() - assessed
  ) %>%
  pivot_longer(assessed:missing, names_to = "cmpl_type", values_to = "n") %>%
  mutate(
    cmpl_type = recode_factor(
      cmpl_type,
      missing = "未完成测评",
      assessed = "已完成测评"
    )
  ) %>%
  ggplot(
    aes(
      school, n, fill = cmpl_type,
      label = if_else(
        n == 0, NA_character_,
        paste0(round(n / n_total * 100, 0), "%")
      )
    )
  ) +
  geom_bar(stat = "identity") +
  geom_text(
    aes(color = cmpl_type),
    position = position_stack(vjust = 0.5)
  ) +
  scale_y_continuous() +
  scale_fill_brewer(palette = "Paired") +
  scale_color_brewer(palette = "Spectral", guide = FALSE) +
  coord_flip() +
  labs(x = "", y = "人数", fill = "") +
  theme_few(base_size = 15, base_family = text_family) +
  theme(legend.position = "top")
```

图\@ref(fig:school-summary)中展示了本次测评各学校完成情况。其中未测的人数是指没有任何测评数据的学生数目，这些学生将不包括在后面的报告中。

```{r sex-summary, fig.width=4, fig.height=4, fig.cap="已测学生男女人数比例"}
tbl_sex <- ability_scores %>%
  select(-ab_name) %>%
  spread(ab_code, score) %>%
  right_join(users_to_report, by = "user_id") %>%
  mutate(n_total = sum(!is.na(assess_time))) %>%
  group_by(user_sex, n_total) %>%
  summarise(n = sum(!is.na(assess_time)))
tbl_sex %>%
  ggplot(aes("", n / n_total, fill = user_sex,
             label = str_glue("{user_sex}（{n}，{round(n / n_total * 100)}%）"))) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  geom_text(position = position_stack(vjust = 0.5), color = "white", family = text_family) +
  scale_fill_brewer(palette = "Accent", guide = FALSE) +
  coord_polar("y", start = 0) +
  theme_void(base_size = 15, base_family = text_family)
```

图\@ref(fig:sex-summary)展示了实际参与测评的学生男女人数比例。其中，`r with(tbl_sex, user_sex[which.max(n)])`生占比相对更大。

```{r grade-summary, fig.width=8, fig.height=6, fig.cap="各年级完成测评人数情况"}
tbl_grade <- ability_scores %>%
  select(-ab_name) %>%
  spread(ab_code, score) %>%
  right_join(users_to_report, by = "user_id") %>%
  group_by(grade) %>%
  summarise(n = sum(!is.na(assess_time)))
tbl_grade %>%
  ggplot(aes(grade, n, label = n)) +
  geom_bar(stat = "identity", width = 0.6, fill = "lightblue") +
  geom_text(color = "red", family = text_family) +
  labs(x = "", y = "完成测评人数") +
  theme_few(base_size = 15, base_family = text_family)
```

图\@ref(fig:grade-summary)展示了整个区域各年级完成测评人数比例。
